"""
Adaptive Reasoning Engine Architecture

This module defines the core architecture for the adaptive reasoning system,
providing the foundation for intelligent decision-making based on hierarchical
context access and strategy selection.

Reasoning Pipeline:
    1. Analyze: Analyze current context and situation
    2. Decide: Select best action based on context
    3. Act: Execute selected action
    4. Validate: Validate result and update context

Reasoning Strategies:
    - Conservative: More context, safer actions, slower
    - Balanced: Moderate context, optimal actions
    - Aggressive: Minimal context, faster actions, higher risk
"""

from enum import Enum
from typing import Optional, Dict, Any, List, Callable
from dataclasses import dataclass
import logging
from datetime import datetime

logger = logging.getLogger(__name__)


class ReasoningStrategy(str, Enum):
    """Available reasoning strategies"""
    CONSERVATIVE = "conservative"
    BALANCED = "balanced"
    AGGRESSIVE = "aggressive"


class SituationType(str, Enum):
    """Types of situations the reasoning engine can encounter"""
    NORMAL = "normal"
    ERROR = "error"
    BLOCKED = "blocked"
    UNCERTAIN = "uncertain"
    COMPLEX = "complex"
    TIME_CRITICAL = "time_critical"
    RECOVERY = "recovery"


@dataclass
class SituationReport:
    """Report generated by context analysis"""
    situation_type: SituationType
    confidence: float
    features: Dict[str, Any]
    potential_actions: List[str]
    risks: List[str]
    constraints: List[str]
    recommendations: List[str]
    timestamp: datetime


@dataclass
class Decision:
    """Represents a decision made by the reasoning engine"""
    action: str
    strategy: ReasoningStrategy
    reasoning: str
    confidence: float
    alternatives: List[Dict[str, Any]]  # [{"action": "...", "reason_for_rejection": "..."}]
    expected_outcome: str
    risk_level: float
    time_estimate: float
    resource_estimate: Dict[str, Any]


@dataclass
class ValidationResult:
    """Result of action validation"""
    success: bool
    goal_achieved: bool
    side_effects: List[str]
    progress_made: float
    efficiency_score: float
    error_message: Optional[str]
    corrections_needed: List[str]


@dataclass
class ReasoningMetrics:
    """Metrics for reasoning engine performance"""
    total_decisions: int = 0
    successful_decisions: int = 0
    success_rate: float = 0.0
    average_confidence: float = 0.0
    average_time_seconds: float = 0.0
    strategy_usage: Dict[ReasoningStrategy, int] = None
    strategy_success_rates: Dict[ReasoningStrategy, float] = None
    
    def __post_init__(self):
        if self.strategy_usage is None:
            self.strategy_usage = {strategy: 0 for strategy in ReasoningStrategy}
        if self.strategy_success_rates is None:
            self.strategy_success_rates = {strategy: 0.0 for strategy in ReasoningStrategy}


class ReasoningEngine:
    """
    Adaptive Reasoning Engine
    
    This engine provides intelligent decision-making by:
    1. Analyzing context to understand the situation
    2. Selecting appropriate reasoning strategy
    3. Making decisions with confidence estimation
    4. Validating results and learning from outcomes
    """
    
    def __init__(
        self,
        context_hierarchy_manager=None,
        telemetry_manager=None,
        default_strategy: ReasoningStrategy = ReasoningStrategy.BALANCED,
        confidence_threshold: float = 0.7
    ):
        """
        Initialize the reasoning engine
        
        Args:
            context_hierarchy_manager: Manager for accessing hierarchical context
            telemetry_manager: Manager for tracking reasoning operations
            default_strategy: Default reasoning strategy to use
            confidence_threshold: Minimum confidence threshold for decisions
        """
        self.context_hierarchy = context_hierarchy_manager
        self.telemetry = telemetry_manager
        self.default_strategy = default_strategy
        self.confidence_threshold = confidence_threshold
        
        # Reasoning metrics
        self.metrics = ReasoningMetrics()
        
        # Strategy selection matrix (situation -> strategy probabilities)
        self.strategy_selection_matrix = {
            SituationType.NORMAL: {
                ReasoningStrategy.CONSERVATIVE: 0.2,
                ReasoningStrategy.BALANCED: 0.6,
                ReasoningStrategy.AGGRESSIVE: 0.2
            },
            SituationType.ERROR: {
                ReasoningStrategy.CONSERVATIVE: 0.7,
                ReasoningStrategy.BALANCED: 0.25,
                ReasoningStrategy.AGGRESSIVE: 0.05
            },
            SituationType.BLOCKED: {
                ReasoningStrategy.CONSERVATIVE: 0.7,
                ReasoningStrategy.BALANCED: 0.25,
                ReasoningStrategy.AGGRESSIVE: 0.05
            },
            SituationType.UNCERTAIN: {
                ReasoningStrategy.CONSERVATIVE: 0.4,
                ReasoningStrategy.BALANCED: 0.5,
                ReasoningStrategy.AGGRESSIVE: 0.1
            },
            SituationType.COMPLEX: {
                ReasoningStrategy.CONSERVATIVE: 0.4,
                ReasoningStrategy.BALANCED: 0.5,
                ReasoningStrategy.AGGRESSIVE: 0.1
            },
            SituationType.TIME_CRITICAL: {
                ReasoningStrategy.CONSERVATIVE: 0.1,
                ReasoningStrategy.BALANCED: 0.3,
                ReasoningStrategy.AGGRESSIVE: 0.6
            },
            SituationType.RECOVERY: {
                ReasoningStrategy.CONSERVATIVE: 0.7,
                ReasoningStrategy.BALANCED: 0.25,
                ReasoningStrategy.AGGRESSIVE: 0.05
            }
        }
        
        # Strategy performance tracking
        self.strategy_performance: Dict[ReasoningStrategy, Dict[str, float]] = {
            strategy: {
                "total": 0,
                "successful": 0,
                "average_time": 0.0,
                "average_confidence": 0.0
            }
            for strategy in ReasoningStrategy
        }
        
        logger.info(
            "ReasoningEngine initialized",
            default_strategy=default_strategy.value,
            confidence_threshold=confidence_threshold
        )
    
    def analyze(self, context: Dict[str, Any]) -> SituationReport:
        """
        Analyze current context to understand the situation
        
        Args:
            context: Current context dictionary
            
        Returns:
            SituationReport with analysis results
        """
        logger.debug("Starting context analysis")
        
        # Extract features from context
        features = self._extract_features(context)
        
        # Classify situation type
        situation_type = self._classify_situation(features)
        
        # Estimate confidence based on context completeness
        confidence = self._estimate_confidence(context, features)
        
        # Identify potential actions
        potential_actions = self._identify_potential_actions(
            situation_type, features
        )
        
        # Identify risks
        risks = self._identify_risks(situation_type, features)
        
        # Identify constraints
        constraints = self._identify_constraints(context, features)
        
        # Generate recommendations
        recommendations = self._generate_recommendations(
            situation_type, features, risks, constraints
        )
        
        report = SituationReport(
            situation_type=situation_type,
            confidence=confidence,
            features=features,
            potential_actions=potential_actions,
            risks=risks,
            constraints=constraints,
            recommendations=recommendations,
            timestamp=datetime.now()
        )
        
        logger.info(
            "Context analysis complete",
            situation_type=situation_type.value,
            confidence=confidence,
            potential_actions_count=len(potential_actions)
        )
        
        # Track in telemetry if available
        if self.telemetry:
            self.telemetry.record_event(
                event_type="reasoning_analyze",
                severity="info",
                context={
                    "situation_type": situation_type.value,
                    "confidence": confidence
                }
            )
        
        return report
    
    def decide(
        self,
        situation_report: SituationReport,
        context: Dict[str, Any],
        strategy: Optional[ReasoningStrategy] = None
    ) -> Decision:
        """
        Select best action based on context analysis
        
        Args:
            situation_report: Report from context analysis
            context: Current context dictionary
            strategy: Optional strategy override (otherwise selected automatically)
            
        Returns:
            Decision with action selection and reasoning
        """
        logger.debug("Starting decision making")
        
        # Select reasoning strategy
        if strategy is None:
            strategy = self._select_strategy(situation_report)
        
        # Identify potential actions
        actions = situation_report.potential_actions
        
        if not actions:
            # Fallback: no clear actions available
            return Decision(
                action="wait_for_human_intervention",
                strategy=strategy,
                reasoning="No clear actions available in current situation",
                confidence=0.0,
                alternatives=[],
                expected_outcome="Human will provide guidance",
                risk_level=1.0,
                time_estimate=0.0,
                resource_estimate={}
            )
        
        # Evaluate each action
        evaluated_actions = [
            self._evaluate_action(action, strategy, situation_report, context)
            for action in actions
        ]
        
        # Select best action
        best_action = max(evaluated_actions, key=lambda x: x["score"])
        
        # Generate decision
        decision = Decision(
            action=best_action["action"],
            strategy=strategy,
            reasoning=best_action["reasoning"],
            confidence=best_action["confidence"],
            alternatives=[
                {
                    "action": action["action"],
                    "reason_for_rejection": action["rejection_reason"]
                }
                for action in evaluated_actions
                if action["action"] != best_action["action"]
            ],
            expected_outcome=best_action["expected_outcome"],
            risk_level=best_action["risk_level"],
            time_estimate=best_action["time_estimate"],
            resource_estimate=best_action["resource_estimate"]
        )
        
        logger.info(
            "Decision made",
            action=decision.action,
            strategy=strategy.value,
            confidence=decision.confidence,
            risk_level=decision.risk_level
        )
        
        # Track decision in telemetry
        if self.telemetry:
            self.telemetry.record_event(
                event_type="reasoning_decide",
                severity="info",
                context={
                    "action": decision.action,
                    "strategy": strategy.value,
                    "confidence": decision.confidence,
                    "risk_level": decision.risk_level
                }
            )
        
        # Update metrics
        self._record_decision(decision)
        
        return decision
    
    def act(self, decision: Decision, action_executor: Callable) -> Any:
        """
        Execute selected action
        
        Args:
            decision: Decision object with action to execute
            action_executor: Function to execute the action
            
        Returns:
            Result of action execution
        """
        logger.info(
            "Executing action",
            action=decision.action,
            strategy=decision.strategy.value
        )
        
        # Start tracking action execution
        if self.telemetry:
            operation = self.telemetry.start_operation(
                operation_type="reasoning_act",
                title=f"Execute action: {decision.action}",
                context={"strategy": decision.strategy.value}
            )
        
        try:
            # Execute the action
            result = action_executor(decision)
            
            logger.info(
                "Action executed successfully",
                action=decision.action
            )
            
            # Record success in telemetry
            if self.telemetry:
                self.telemetry.record_metric(
                    metric_name="action_success",
                    metric_value=1.0,
                    operation_id=operation.operation_id
                )
                operation.end()
            
            return result
            
        except Exception as e:
            logger.error(
                "Action execution failed",
                action=decision.action,
                error=str(e)
            )
            
            # Record failure in telemetry
            if self.telemetry:
                self.telemetry.record_metric(
                    metric_name="action_success",
                    metric_value=0.0,
                    operation_id=operation.operation_id
                )
                self.telemetry.record_event(
                    event_type="action_failed",
                    severity="error",
                    context={
                        "action": decision.action,
                        "error": str(e)
                    },
                    operation_id=operation.operation_id
                )
                operation.end()
            
            raise
    
    def validate(
        self,
        decision: Decision,
        result: Any,
        context: Dict[str, Any]
    ) -> ValidationResult:
        """
        Validate that action achieved intended result
        
        Args:
            decision: Decision object with expected outcome
            result: Actual result of action execution
            context: Current context after action
            
        Returns:
            ValidationResult with validation results
        """
        logger.debug("Starting action validation")
        
        # Check if goal was achieved
        goal_achieved = self._check_goal_achieved(decision, result)
        
        # Check for side effects
        side_effects = self._check_side_effects(decision, result, context)
        
        # Measure progress
        progress_made = self._measure_progress(decision, result, context)
        
        # Calculate efficiency
        efficiency_score = self._calculate_efficiency(decision, result)
        
        # Determine overall success
        success = goal_achieved and len(side_effects) == 0 and progress_made > 0
        
        # Identify corrections needed
        corrections_needed = []
        if not goal_achieved:
            corrections_needed.append("Goal not achieved, retry with different approach")
        if side_effects:
            corrections_needed.append(f"Address side effects: {', '.join(side_effects)}")
        if progress_made <= 0:
            corrections_needed.append("No progress made, reconsider approach")
        
        validation_result = ValidationResult(
            success=success,
            goal_achieved=goal_achieved,
            side_effects=side_effects,
            progress_made=progress_made,
            efficiency_score=efficiency_score,
            error_message=None if success else "Validation failed",
            corrections_needed=corrections_needed
        )
        
        logger.info(
            "Validation complete",
            success=success,
            goal_achieved=goal_achieved,
            progress_made=progress_made,
            efficiency_score=efficiency_score
        )
        
        # Update strategy performance based on validation
        self._update_strategy_performance(decision.strategy, validation_result)
        
        # Track in telemetry
        if self.telemetry:
            self.telemetry.record_event(
                event_type="reasoning_validate",
                severity="info" if success else "warning",
                context={
                    "success": success,
                    "goal_achieved": goal_achieved,
                    "progress_made": progress_made,
                    "efficiency_score": efficiency_score,
                    "strategy": decision.strategy.value
                }
            )
        
        return validation_result
    
    def get_metrics(self) -> ReasoningMetrics:
        """
        Get current reasoning metrics
        
        Returns:
            ReasoningMetrics with performance statistics
        """
        # Calculate success rate
        if self.metrics.total_decisions > 0:
            self.metrics.success_rate = (
                self.metrics.successful_decisions / self.metrics.total_decisions
            )
        
        # Calculate strategy success rates
        for strategy in ReasoningStrategy:
            perf = self.strategy_performance[strategy]
            if perf["total"] > 0:
                self.metrics.strategy_success_rates[strategy] = (
                    perf["successful"] / perf["total"]
                )
        
        return self.metrics
    
    def _extract_features(self, context: Dict[str, Any]) -> Dict[str, Any]:
        """Extract key features from context"""
        features = {
            "error_frequency": 0,
            "task_complexity": "medium",
            "resource_availability": "good",
            "time_pressure": "normal",
            "progress_rate": 0.0
        }
        
        # Extract from context if available
        if "recent_errors" in context:
            features["error_frequency"] = len(context["recent_errors"])
        
        if "task" in context:
            task = context["task"]
            features["task_complexity"] = task.get("complexity", "medium")
        
        if "resources" in context:
            resources = context["resources"]
            features["resource_availability"] = resources.get("status", "good")
        
        if "progress" in context:
            features["progress_rate"] = context["progress"].get("rate", 0.0)
        
        return features
    
    def _classify_situation(self, features: Dict[str, Any]) -> SituationType:
        """Classify situation based on features"""
        # Check for error situation
        if features["error_frequency"] > 0:
            return SituationType.ERROR
        
        # Check for blocked situation
        if features.get("blocked", False):
            return SituationType.BLOCKED
        
        # Check for time-critical situation
        if features.get("time_pressure") == "critical":
            return SituationType.TIME_CRITICAL
        
        # Check for complex situation
        if features["task_complexity"] == "high":
            return SituationType.COMPLEX
        
        # Check for uncertain situation
        if features.get("confidence", 1.0) < self.confidence_threshold:
            return SituationType.UNCERTAIN
        
        # Default to normal
        return SituationType.NORMAL
    
    def _estimate_confidence(self, context: Dict[str, Any], features: Dict[str, Any]) -> float:
        """Estimate confidence in context analysis"""
        confidence = 1.0
        
        # Reduce confidence if errors present
        if features["error_frequency"] > 0:
            confidence -= 0.2 * min(features["error_frequency"], 3)
        
        # Reduce confidence if context incomplete
        if not context.get("complete", False):
            confidence -= 0.1
        
        # Reduce confidence if resources limited
        if features["resource_availability"] != "good":
            confidence -= 0.15
        
        return max(0.0, min(1.0, confidence))
    
    def _identify_potential_actions(
        self,
        situation_type: SituationType,
        features: Dict[str, Any]
    ) -> List[str]:
        """Identify potential actions for given situation"""
        # This is a placeholder - actual implementation would use LLM or rules
        actions = []
        
        if situation_type == SituationType.NORMAL:
            actions = ["continue_current_task", "take_next_step"]
        elif situation_type == SituationType.ERROR:
            actions = ["retry_with_backoff", "try_alternative_approach", "rollback"]
        elif situation_type == SituationType.BLOCKED:
            actions = ["seek_alternative_path", "break_down_task", "request_help"]
        elif situation_type == SituationType.TIME_CRITICAL:
            actions = ["skip_optional_steps", "use_fast_approach", "parallelize"]
        
        return actions
    
    def _identify_risks(self, situation_type: SituationType, features: Dict[str, Any]) -> List[str]:
        """Identify risks in current situation"""
        risks = []
        
        if features["error_frequency"] > 0:
            risks.append("Recurring errors may indicate deeper issue")
        
        if features["resource_availability"] != "good":
            risks.append("Limited resources may cause failures")
        
        if features["progress_rate"] < 0.1:
            risks.append("Slow progress may indicate stuck state")
        
        return risks
    
    def _identify_constraints(
        self,
        context: Dict[str, Any],
        features: Dict[str, Any]
    ) -> List[str]:
        """Identify constraints on decision making"""
        constraints = []
        
        if features["resource_availability"] != "good":
            constraints.append("Minimize resource usage")
        
        if features["time_pressure"] == "critical":
            constraints.append("Minimize time to completion")
        
        if features["task_complexity"] == "high":
            constraints.append("Use conservative approach for safety")
        
        return constraints
    
    def _generate_recommendations(
        self,
        situation_type: SituationType,
        features: Dict[str, Any],
        risks: List[str],
        constraints: List[str]
    ) -> List[str]:
        """Generate recommendations based on analysis"""
        recommendations = []
        
        if situation_type == SituationType.ERROR:
            recommendations.append("Use conservative strategy for error recovery")
        
        if features["progress_rate"] < 0.1:
            recommendations.append("Consider alternative approach if no progress")
        
        if features["resource_availability"] != "good":
            recommendations.append("Optimize resource usage")
        
        return recommendations
    
    def _select_strategy(self, situation_report: SituationReport) -> ReasoningStrategy:
        """Select reasoning strategy based on situation"""
        # Get strategy probabilities for situation type
        strategy_probs = self.strategy_selection_matrix.get(
            situation_report.situation_type,
            self.strategy_selection_matrix[SituationType.NORMAL]
        )
        
        # For now, select strategy with highest probability
        # In future, use weighted random selection or learning
        best_strategy = max(strategy_probs.items(), key=lambda x: x[1])[0]
        
        logger.debug(
            "Strategy selected",
            situation=situation_report.situation_type.value,
            strategy=best_strategy.value
        )
        
        return best_strategy
    
    def _evaluate_action(
        self,
        action: str,
        strategy: ReasoningStrategy,
        situation_report: SituationReport,
        context: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Evaluate an action for selection"""
        # Placeholder evaluation - actual implementation would be more sophisticated
        # Factors: success probability, cost, risk, time
        
        score = 0.5  # Base score
        confidence = 0.5
        reasoning = f"Selected based on {strategy.value} strategy"
        expected_outcome = "Progress toward goal"
        risk_level = 0.3
        time_estimate = 1.0
        resource_estimate = {"tokens": 100}
        
        # Adjust based on strategy
        if strategy == ReasoningStrategy.CONSERVATIVE:
            risk_level = 0.1
            confidence = 0.7
            time_estimate = 2.0
            resource_estimate["tokens"] = 200
            score = 0.6
        elif strategy == ReasoningStrategy.AGGRESSIVE:
            risk_level = 0.6
            confidence = 0.4
            time_estimate = 0.5
            resource_estimate["tokens"] = 50
            score = 0.5
        else:  # BALANCED
            risk_level = 0.3
            confidence = 0.6
            time_estimate = 1.0
            resource_estimate["tokens"] = 100
            score = 0.7
        
        return {
            "action": action,
            "score": score,
            "confidence": confidence,
            "reasoning": reasoning,
            "expected_outcome": expected_outcome,
            "risk_level": risk_level,
            "time_estimate": time_estimate,
            "resource_estimate": resource_estimate,
            "rejection_reason": "Lower score than selected action"
        }
    
    def _check_goal_achieved(self, decision: Decision, result: Any) -> bool:
        """Check if action achieved intended goal"""
        # Placeholder - actual implementation would check against expected outcome
        return True
    
    def _check_side_effects(
        self,
        decision: Decision,
        result: Any,
        context: Dict[str, Any]
    ) -> List[str]:
        """Check for unintended side effects"""
        # Placeholder - actual implementation would analyze changes
        return []
    
    def _measure_progress(
        self,
        decision: Decision,
        result: Any,
        context: Dict[str, Any]
    ) -> float:
        """Measure progress toward goal"""
        # Placeholder - actual implementation would calculate actual progress
        return 0.1  # 10% progress
    
    def _calculate_efficiency(self, decision: Decision, result: Any) -> float:
        """Calculate efficiency score"""
        # Placeholder - actual implementation would compare resources used vs expected
        return 0.8  # 80% efficient
    
    def _record_decision(self, decision: Decision):
        """Record decision in metrics"""
        self.metrics.total_decisions += 1
        self.metrics.strategy_usage[decision.strategy] += 1
        
        # Update average confidence
        total_confidence = (
            self.metrics.average_confidence * (self.metrics.total_decisions - 1)
        )
        self.metrics.average_confidence = (
            (total_confidence + decision.confidence) / self.metrics.total_decisions
        )
    
    def _update_strategy_performance(
        self,
        strategy: ReasoningStrategy,
        validation_result: ValidationResult
    ):
        """Update strategy performance metrics based on validation"""
        perf = self.strategy_performance[strategy]
        perf["total"] += 1
        
        if validation_result.success:
            perf["successful"] += 1
        
        # Update average efficiency
        total_efficiency = perf["average_efficiency"] * (perf["total"] - 1)
        perf["average_efficiency"] = (
            (total_efficiency + validation_result.efficiency_score) / perf["total"]
        )